version: '3'
services:
  app:
    build: ./docker/app
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - ./src:/var/www/app
      - ./docker/schemaspy/output:/var/www/html
    working_dir: /var/www/app

  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    env_file:
      - ./docker/db/.env
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/sql:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 4040:80
    depends_on:
      - db
    env_file:
      - ./docker/phpmyadmin/.env
    links:
      - db
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions

  schemaspy:
    build: ./docker/schemaspy
    depends_on:
      - db
    volumes:
      - ./docker/schemaspy/output:/output
    command: [ "-configFile", "/config/schemaspy.properties" ]
