FROM schemaspy/schemaspy

# JDBC ドライバをインストール
ADD http://search.maven.org/remotecontent?filepath=mysql/mysql-connector-java/8.0.16/mysql-connector-java-8.0.16.jar \
    /drivers/mysql-connector-java-8.0.16.jar

# 設定ファイルを配置
ADD config /config